@startuml US108-SD
skinparam sequenceMessageAlign center

actor "Backoffice Operator / ATCC" as Actor
participant "«filter»\nJwtAuthenticationFilter" as Filter
participant "AirportController" as Controller
participant "SearchAirportsUseCaseImpl" as UseCase
participant "AirportRepository" as Repo

autonumber

Actor -> Filter : GET /airports?city=Lisbon&country=Portugal\nAccept: application/hal+json
activate Filter

note right of Filter
  See security/SD-AuthFilter.puml
  Required role(s) for this US: BACKOFFICE_OPERATOR, ATCC
end note

Filter -> Controller : forward authenticated request
deactivate Filter
activate Controller

Controller -> UseCase : searchAirports(name, city, country)
activate UseCase

UseCase -> Repo : searchByCriteria(name, city, country)
activate Repo

Repo --> UseCase : List<Airport>
deactivate Repo

UseCase --> Controller : List<Airport>
deactivate UseCase


Controller --> Actor : 200 OK\n{ "_embedded": { "airports": [...] },\n  "_links": { "self": "..." } }

deactivate Controller
@enduml
