@startuml US104-CD
skinparam classAttributeIconSize 0

class AircraftRestController {
  + searchAircrafts(model: String, status: String, year: Integer, pageable: Pageable, pagedAssembler: PagedResourcesAssembler): ResponseEntity<PagedModel<EntityModel<AircraftDTO>>>
}

class SearchAircraftService {
  + searchAircrafts(model: String, status: String, year: Integer, pageable: Pageable): Page<Aircraft>
}

interface AircraftRepository <<Repository>> {
  + findAll(spec: Specification<Aircraft>, pageable: Pageable): Page<Aircraft>
}

class AircraftAssembler {
  + toModel(aircraft: Aircraft): EntityModel<AircraftDTO>
}

AircraftRestController ..> SearchAircraftService
AircraftRestController ..> AircraftAssembler
SearchAircraftService ..> AircraftRepository
@enduml