@startuml
autonumber
actor "ATCC" as ATCC
participant "System" as SYS

activate ATCC
ATCC -> SYS : GET /api/aircrafts/{registrationNumber}/status
activate SYS
SYS --> ATCC : 200 OK (Returns real-time status of the aircraft)
deactivate SYS
deactivate ATCC
@enduml