@startuml
autonumber
actor "ATCC" as ATCC
participant "System" as SYS

activate ATCC
ATCC -> SYS : GET /api/scheduled-flights?aircraft={registration}
activate SYS

SYS --> ATCC : 200 OK (paginated list of Scheduled Flights)
deactivate SYS
deactivate ATCC
@enduml
