@startuml
autonumber
actor "ATCC" as ATCC
participant "System" as SYS

activate ATCC
ATCC -> SYS : POST /api/scheduled-flights (aircraft, routeID, date, time)
activate SYS

SYS --> ATCC : 201 Created (ScheduledFlight details)
deactivate SYS
deactivate ATCC
@enduml
