@startuml
hide methods

entity MaintenanceRecord <<Entity>> <<Root>> {
  version
  status: MaintenanceStatus
}

enum MaintenanceStatus <<Value Object>> {
  PLANNED
  ONGOING
  PAUSED
  COMPLETED
  CANCELLED
}

MaintenanceRecord --> "1" MaintenanceStatus
@enduml