@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

class AircraftModel <<Aggregate Root>> <<Entity>> {
}

class ModelImage <<Value Object>> {
  - imageUrl : String
}

class ModelDesignation <<Value Object>> <<ID>> {
  - manufacturer : String
  - modelName : String
}

class ModelSpecifications <<Value Object>> {
  - standardSeatingCapacity : Integer
}

AircraftModel "1" --> "1" ModelDesignation : identified by >
AircraftModel "1" --> "1" ModelSpecifications : described by >
AircraftModel "1" --> "0..1" ModelImage : visually represented by >

note bottom of ModelImage
  Optional attribute introduced in Phase 2
end note

@enduml