@startuml
autonumber
actor "ATCC" as ATCC
participant "System" as SYS

activate ATCC
ATCC -> SYS : GET /api/routes/active?sortBy={popularity|distance}
activate SYS

SYS --> ATCC : 200 OK (sorted list of active routes)
deactivate SYS
deactivate ATCC
@enduml
