@startuml US104-SSD
autonumber
actor "ATCC" as User
participant "System" as SYS

activate User
User -> SYS : GET /api/aircrafts?model={x}&status={y}&year={z}&page={p}&size={s}
activate SYS

SYS --> User : 200 OK (Paginated List of Aircraft DTOs)
deactivate SYS
deactivate User
@enduml