spring.application.name=aisafe

# Configuração da Base de Dados H2
spring.datasource.url=jdbc:h2:mem:aisafedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Permite que o Spring crie as tabelas na base de dados automaticamente baseado Entidades
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Ativa a consola do H2 no browser 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
