@startuml
autonumber
actor "System" as System
actor "ATCC" as ATCC

System -> System : periodic check of maintenance limits
activate System
System -> ATCC : issues alert (aircraft X due for template Y)
deactivate System
@enduml